version: '3'
services:
  php-fpm:
    labels:
      com.example.description: "This label will appear on all containers for the web service"
    image: devel:5000/c6-php54:latest
    #hostname: php5.4
    networks:
      #ingress:
      #  aliases:
      #    - php5.4
      #    #- php
      9znet:
        aliases:
          - php5.4
    volumes:
      - data:/opt/www
    deploy:
      #placement:
        #constraints: [node.role == manager]
        #constraints: [node.hostname == test-248]
      labels:
        com.example.description: "This label will appear on the web service"
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

volumes:
  data:
    external:
      name: data

networks:  
  9znet:
    external: true
    #ipam:
    #  config:
    #    - subnet: 172.16.1.0/24
          #gateway: 172.16.1.1
