version: "3.1"
services:
  http:
    image: devel:5000/nginx:1.10.2
    deploy:
      replicas: 1
    secrets:
      - port
      - ip
    environment:
      - php_server=/run/secrets/ip
      - port=/run/secrets/port
secrets:
  ip:
    file: ./ip.txt
  port:
    external: true
